### ISSUE TITLE
Create User Model 

### ISSUE THREAD

**Issue by francofin** [francofin/Hire#3]
1. User Image (optional)
2. User Name
3. Years of Experience
4. Top Skill (selected from OUR LIST)
5. Other Skills (selected from OUR LIST)
6. Contact information
   1. Phone number
   2. Email
   3. Linked-in
   4. GitHub

11. List of projects you are actively involved in (on this site/app)

**Comment by SterlynKong** [comment]
We need to add Phone Number, Linked-In and GitHub to the User model @francofin @SterlynKong
